# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-dispatcher" do
  version "3.9.0"

  on_macos do
    on_arm do
      sha256 "c98d55bdf58de83e1a2e0c6d2356a16c70a830d81decde09988f0db76e8070cb"
      url "https://github.com/Innovology/claude-dispatcher/releases/download/v#{version}/claude-dispatcher_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b9f6f8ddab5f82b2cdacbc3f7387729cf59637f20b56fdf43a0dd85eef84834b"
      url "https://github.com/Innovology/claude-dispatcher/releases/download/v#{version}/claude-dispatcher_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7ed0cb6993143ad1650529594f5d2f11ac7665dad05bf3b93312a73c88633fbf"
      url "https://github.com/Innovology/claude-dispatcher/releases/download/v#{version}/claude-dispatcher_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cafd2e710371b9ae16b88838ae8ef04e30634eb49b7e1a16a27226e70776ed26"
      url "https://github.com/Innovology/claude-dispatcher/releases/download/v#{version}/claude-dispatcher_#{version}_linux_amd64.tar.gz"
    end
  end

  name "claude-dispatcher"
  desc "Terminal dispatch cockpit for Claude Code sessions across many repositories"
  homepage "https://github.com/Innovology/claude-dispatcher"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "claude-dispatcher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-dispatcher"], must_succeed: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Requires the claude CLI (Claude Code) on your PATH.
    Run `claude-dispatcher init` to configure repo roots and install the
    status hook.
  EOS
end
