# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-dispatcher" do
  version "3.11.1"

  on_macos do
    on_arm do
      sha256 "376d23a115fcfb39f1046dc0e31bce266192ab2509187f8d8f5d1cd54f37cd1a"
      url "https://github.com/Innovology/claude-dispatcher/releases/download/v#{version}/claude-dispatcher_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b98fbb7da85b5de275cd5d32029921e79acdf09350c1a603e499531c4a6b7e92"
      url "https://github.com/Innovology/claude-dispatcher/releases/download/v#{version}/claude-dispatcher_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fd627a2b1481b16286cd1861f6038613193f9a8bdc8fa0bdae02d65a397db986"
      url "https://github.com/Innovology/claude-dispatcher/releases/download/v#{version}/claude-dispatcher_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e83e6ada76277052aef6674521b3ba16ae587ff5a8c806b67e48c22e85083f1b"
      url "https://github.com/Innovology/claude-dispatcher/releases/download/v#{version}/claude-dispatcher_#{version}_linux_amd64.tar.gz"
    end
  end

  name "claude-dispatcher"
  desc "Terminal dispatch cockpit for Claude Code sessions across many repositories"
  homepage "https://github.com/Innovology/claude-dispatcher"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "claude-dispatcher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-dispatcher"], must_succeed: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Requires the claude CLI (Claude Code) on your PATH.
    Run `claude-dispatcher init` to configure repo roots and install the
    status hook.
  EOS
end
