# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-dispatcher" do
  version "3.1.5"

  on_macos do
    on_intel do
      sha256 "0c507e094838d2fcfe6c96dbd5035e27f1c539490dacb61a142868cee3929a7a"
      url "https://github.com/Innovology/claude-dispatcher/releases/download/v#{version}/claude-dispatcher_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e8dd4e64a88f7f680f6d7ef09a2850be96a6fd6dc93af34574ce1fa85ae5cd3"
      url "https://github.com/Innovology/claude-dispatcher/releases/download/v#{version}/claude-dispatcher_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e2b52401aab6a16afbea6f441ad3c9278d9f6330ac1773c033116e3a0578dee1"
      url "https://github.com/Innovology/claude-dispatcher/releases/download/v#{version}/claude-dispatcher_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc663e42dba09c69b106cef07e59dd1028ade04c45dba608060f96b1537c0e4f"
      url "https://github.com/Innovology/claude-dispatcher/releases/download/v#{version}/claude-dispatcher_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-dispatcher"
  desc "Terminal dispatch cockpit for Claude Code sessions across many repositories"
  homepage "https://github.com/Innovology/claude-dispatcher"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "claude-dispatcher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-dispatcher"], must_succeed: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Requires the claude CLI (Claude Code) on your PATH.
    Run `claude-dispatcher init` to configure repo roots and install the
    status hook.
  EOS
end
